### ISSUE TITLE
Getting html instead of JSON

### ISSUE THREAD

**Issue by FelipeSBarros** [voltdatalab/crossfire#1]
Hi, I've been traying to use crossfire api with r package.
But I got an error when using any of functions to retrieve data...
```
get_fogocruzado(city = c("Rio de Janeiro"),
+                                          initial_date = "2018-01-01", final_date = "2018-12-31")

Extracting data from Fogo Cruzado's API.
 
...

Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html> <!--[if lt IE 7
                     (right here) ------^
```
Am I doing something wrong?
Best regards
Felipe

**Comment by lgelape** [comment]
With the new API version, we updated `crossfire` to v `0.2.0` and users should update the package. 

The error above did not appear (so far) on the new version, so I'm closing the issue.
