### ISSUE TITLE
Python package

### ISSUE THREAD

**Issue by FelipeSBarros** [voltdatalab/crossfire#2]
Hello there!
Just to let you know that I will try creating a crossfire python package.
Not sure if I will be able to accomplish nor  when...

**Comment by sergiospagnuolo** [comment]
Boa iniciativa! Avisa a gente.

**Comment by FelipeSBarros** [comment]
@sergiospagnuolo e @lgelape vou criar uma pasta "Python" e desenvolver o módulo nele. Alguma orientação quanto a melhor forma de estruturar?

**Comment by sergiospagnuolo** [comment]
o céu é o limite. só deixa bem documentado pros outros saberem utilizar.

**Comment by lgelape** [comment]
@FelipeSBarros em breve deve rolar uma nova versão (melhorada) da API, o que provavelmente exigirá uma atualização do pacote. Vamos atualizar o `crossfire` assim que ela sair (tentando manter a infraestrutura o mais próxima da atual). Então, já fica o aviso de que um pacote em Python teria que ser atualizado em breve, caso isso afete seu processo por aí. 

Conte com a gente em caso de quaisquer dúvidas!

**Comment by FelipeSBarros** [comment]
Perfeito, @sergiospagnuolo . Não era uma questão sobre limites, mas se querem que siga alguma estrutura organizacional.
Entendi que estão abertos a uma proposta minha.
Vou criar uma pasta "Python" onde estará a estrutura de código.

@lgelape , estarei atento. Qaundo estiverem por fazer as mudanças no pacote R, avise. Assim vemos de lançar as atualizações em simultaneo.
Já estou fechando essa implementaão para a versão atual.
Fic com uma dúvida:
Por que em [`get_fogocruzado`](https://github.com/voltdatalab/crossfire/blob/master/R/get_fogocruzado.R), vocês vazem a [conversão sa coluna `cod_ibge_cidade`](https://github.com/voltdatalab/crossfire/blob/master/R/get_fogocruzado.R#L83) ?
`banco.cod_ibge_cidade <- as.character(banco$cod_ibge_cidade)`
abraço
