### ISSUE TITLE
Login Issue: Valid Credentials Rejected

### ISSUE THREAD

**Issue by RKsGIS** [voltdatalab/crossfire#8]
I encountered an issue when using the crossfire library in Python to access the Fogo Cruzado API, specifically when using the fogocruzado_signin function. Despite successfully registering and logging in via a web browser, I am unable to authenticate using the same username and password within the library.

**Comment by sergiospagnuolo** [comment]
Hi, @RKsGIS, this package is no longer maintained by us and I will archive it. Keep in mind that Fogo Cruzado has changed their API and deprecated some endpoints, as far as I know. 

Good luck
